FROM node:18-alpine3.18 as dev

# Install Python and build dependencies for node gyp
# Set Python3 as the default Python version
RUN apk add --no-cache python3 make g++
RUN ln -sf python3 /usr/bin/python

WORKDIR /app/

COPY package*.json .
RUN npm install

COPY . .